### ISSUE TITLE
Provide option to use canary releases?

### ISSUE THREAD

**Issue by 1n5aN1aC** [linuxserver/docker-duplicati#10]
On **November 1st, 2018** Microsoft will be discontinuing the current OneDrive API.  The new graph-based API will be required instead.  (Duplicati 'OneDriveV2')
[Source](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online)

The current Release & beta versions do not have the new backend yet, so all OneDrive backups will likely break tomorrow.  However, it is available in the canary release(s).

An alternate release tag to choose to use the canary versions would be appreciated.  (the opposite of https://github.com/linuxserver/docker-duplicati/issues/2)

Also see [Here](https://forum.duplicati.com/t/onedrivev2-not-available-as-provider-choice/4100) for discussion on it not being available in release/beta yet.

- I am using Docker  version 18.06.1-ce, on Debian Linux.  (Docker-Compose)

**Comment by homerr** [comment]
Thanks for the suggestion however we are not inclined to add a canary option to our container as it is likely to add a large support overhead. We do build on beta releases, so when this goes to beta it will be reflected in our builds.

**Comment by 1n5aN1aC** [comment]
Thanks, understood.
