### ISSUE TITLE
Adding rclone to the Dockerfile

### ISSUE THREAD

**Issue by nicam** [linuxserver/docker-duplicati#13]
Hello Linux Server Team

First of all thanks for your great docker containers.

I was wondering if you could add rclone to this Docker image. Duplicati allows to use rclone as a storage type to access certain storage providers such as pCloud. Also I've seen people using it to access OneDrive as some rewrites in the Duplicati Backend are necessary to make it work again (https://forum.duplicati.com/t/rclone-backend-documentation/2930/7).

Thanks for your help!

**Comment by homerr** [comment]
This sounds like a good addition, I'll work on this and update here as appropriate.

**Comment by nicam** [comment]
Thanks!

**Comment by aptalca** [comment]
No rclone package in the xenial repo. We should add it along with the rebase to bionic

**Comment by homerr** [comment]
If we're to do this it will need a rebase to Bionic. I'll add it to my list.

**Comment by aptalca** [comment]
@nicam 

Can you give this build a try? It is rebased to bionic and has rclone in it
`lsiodev/duplicati:v2.0.4.5-2.0.4.5_beta_2018-11-28-pkg-54fed129-dev-638d5d583e4cf0df70e0c8951f9b2b923d181480`

Once you confirm it works, we'll merge

**Comment by CHBMB** [comment]
@aptalca @homerr Looks like @nicam has gone MIA.....

**Comment by mattohm** [comment]
Getting an error: unknown command "lsjson" for "rclone"

Looks like the version or rclone is too old.

**Comment by aptalca** [comment]
@mattohm need more context
Did you use the build linked above? How did you set up the rclone backend and what activity caused that error? Where did you see the error?

**Comment by aptalca** [comment]
@mattohm I see that the rclone version that ships with bionic is almost 2 years old (does not make much sense, anyway)

Here's a new build with the latest rclone and duplicati canary build: `lsiodev/duplicati:v2.0.4.18-2.0.4.18_canary_2019-05-12-pkg-90e93378-dev-e9647dd5808bcd322a723ee3d30748784f5af717`

You can set up rclone via `docker exec -it duplicati rclone config`, the `rclone.conf` will be created under `/config/rclone`. Or you can manually create that folder and drop your rclone.conf in there. After setting up rclone, restart the container so perms are fixed. Then you should be able to use rclone in duplicati.

Please let us know if that works and we'll merge into development (canary) tag and later the latest (beta) tag.

Thanks

**Comment by aptalca** [comment]
no response from anyone, closing

**Comment by undaunt** [comment]
Hey @aptalca, I'd be happy to test with this if possible. juanheredia seems to already be working on this individually, customizing the linuxserver docker with rclone on his own. It was just rebuilt again today - https://hub.docker.com/r/juanheredia/duplicati-rclone

Please let me know if you or anyone would have time to add it into dev.

Thanks!

**Comment by aptalca** [comment]
I can add this as a [docker mod](https://mods.linuxserver.io/), but based on the previous discussion it didn't seem like there was much interest

**Comment by undaunt** [comment]
I agree, demand seems low. If it's too much of a pain to integration, let's just skip it. If it's trivial, I'd still like to test - not sure how busy you and the team are.

I can still access google drive directly via duplicati, or I could mount the rclone back end in question to a mount point and do a folder backup, so definitely not a strong demand.

Thanks following back up.

**Comment by TheManchineel** [comment]
This is especially useful on a system like Unraid where Rclone can't be really installed natively and the Rclone plugin requires some really bad practices like redownloading the executable from the repository at every boot, since Unraid runs from memory and only uses a USB stick to store configuration and boot files, as if the system was reconfigured/reinstalled at every launch.

**Comment by WoBuGs** [comment]
Is there any chances that this docker mod addition you talked about is still a thing @aptalca?

It would be quite useful to have this possibility instead of manually going into the container and [installing rclone](https://rclone.org/install/#script-installation) when running a new duplicati instance.

**Comment by aptalca** [comment]
You can add a custom script that does it on container start:
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by WoBuGs** [comment]
Oh nice, thank you for the quick reply!
