### ISSUE TITLE
Add --log-file=/config/duplicati.log

### ISSUE THREAD

**Issue by solipsist01** [linuxserver/docker-duplicati#24]
Duplicati logs everything in a sqlite database by default.
It's possible to have a serperate logfile as well.
Could the following syntax be added to the run file:

--log-file=/config/duplicati.log

I could clone this repo and build it myself, but i'd rather pull the images of linuxserver directly.

Thank you.

**Comment by aptalca** [comment]
@solipsist01 I haven't really looked into the logging options in duplicati, but it looks like you can set the `log-file` in the gui settings under default options. Did you give that a try?

**Comment by solipsist01** [comment]
You can close this :) thank you.

Op do 23 mei 2019 23:18 schreef aptalca <notifications@github.com>:
