### ISSUE TITLE
Duplicati in docker container on OMV not reachable via web-ui

### ISSUE THREAD

**Issue by Cantello** [linuxserver/docker-duplicati#25]
The web-ui (supposedly on port 8200) is not reachable when I run duplicati in my docker environment. Duplicati.Server.exe is started with the following script inside the container:
~~~~
#!/usr/bin/with-contenv bash
cd /app/duplicati || exit
 exec \
        s6-setuidgid abc mono Duplicati.Server.exe \
        --webservice-interface=any --webservice-port=8200 --server-datafolder=/config --w$
~~~~
However, I cannot reach anything at port 8200. It is not a local machine but my homelab server in the basement and remote connections should be fine due to the `--webservice-interface=any`. When I enter the container and check with ` lsof -i :8200 | grep LISTEN` if there is something listening at port 8200, it comes up emtpy.
The only thing that I was not really sure about is the `/source` volume for the container - could this be the culprit?

**Host**:

OpenMediaVault/Debian 9.9 (on ESXi if it matters)

**Settings** in OMV, pretty standard:
![image](https://user-images.githubusercontent.com/594700/58155826-fe89b900-7c74-11e9-8356-8b0e0c1f9961.png)
![image](https://user-images.githubusercontent.com/594700/58155847-0c3f3e80-7c75-11e9-8f91-201ca95943fc.png)

**Log output** via `docker logs duplicati`
~~~~
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom scripts found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
~~~~

Any ideas?

**Comment by nemchik** [comment]
Can you post your docker run command or compose?

**Comment by Cantello** [comment]
I no longer use OMV nor Duplicati, have switched to borg & restic now. Can be closed.
