### ISSUE TITLE
Add Support for HTTPS

### ISSUE THREAD

**Issue by Craumix** [linuxserver/docker-duplicati#26]
Thank you guys so much for the image, it has worked great for me so far!

Duplicati supports https using a .p12 certificate via. a command line option:
`--webservice-sslcertificatefile=/tmp/duplicati.p12` [from here](https://forum.duplicati.com/t/duplicati-webserver-https-with-selfsigned-certificate/776)

But I haven't seen any obvious way to use it with the container. Since I don't run the container locally, the only option to access it securely so far is with a VPN connection. Wich, obviously, isn't optimal.

Thanks in advance!

**Comment by aptalca** [comment]
How about a reverse proxy? Check out our letsencrypt image

**Comment by Craumix** [comment]
I would like to avoid any additional setup. Since it already has the functionality I would prefer that over extra container setup.

**Comment by aptalca** [comment]
Feature added in #29 
You can set the `CLI_ARGS` environment variable to add `--webservice-sslcertificatefile=/config/key.p12`
