### ISSUE TITLE
Commandline access

### ISSUE THREAD

**Issue by arberg** [linuxserver/docker-duplicati#33]
It would be great with an alias for the commandline which I found here: 

mono /app/duplicati/Duplicati.CommandLine.exe

Plus info on the dockerhub page (which already contain lots of great documentation)

https://hub.docker.com/r/linuxserver/duplicati/

Manual
https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/

The following worked beautifully outside of the container
alias duplicati=‘docker exec -it duplicati mono /app/duplicati/Duplicati.CommandLine.exe’

With the alias I could do 
duplicati test-filters /mnt/ --exclude='[/mnt/.*]'

**Comment by aptalca** [comment]
Thanks for letting us know, but we'd rather not encourage casual users to use such a highly advanced feature, therefore I'm not for adding it to the readme. Advanced users should be able to figure that out on their own like you did.

**Comment by arberg** [comment]
the downside is only 'advanced' users are able to do what I did to locate the commandline, and the commandline is not inconsequential for duplicati.
