### ISSUE TITLE
Run script after doesn't work (no logs)

### ISSUE THREAD

**Issue by bd8392** [linuxserver/docker-duplicati#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

A Bash script should be executed after a backup
## Current Behavior
"Got 1 Warning" after backup, and script is not executed...
## Steps to Reproduce
1. Define backup job
2. upload a script to a mounted folder, or in root of application
3. define --run-script-after in the backupjob and the location of the script
4. execute backup script
5. get warning and not executed script

## Environment
**OS: rancheros**      
**CPU architecture:** x64    
**How docker service was installed: preinstalled

## Command used to create docker container (run/create/compose/screenshot)
like in docs

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Unable to start up, perhaps another process is already running?
Error message: System.Exception: The lock file was locked, but the locking process did not respond to the start command
  at Duplicati.Server.SingleInstance..ctor (System.String basefolder) [0x0025e] in <c5f097a49c0a4f1fb0f93cf3f5f218b1>:0
  at Duplicati.Server.Program.CreateApplicationInstance (System.Boolean writeConsole) [0x00005] in <c5f097a49c0a4f1fb0f93cf3f5f218b1>:0

**Comment by tobbenb** [comment]
This looks like a support issue and not a bug. Please use our discourse forum or discord for support. GitHub is or bugs.

**Comment by bd8392** [comment]
okay sorry...I did =) : https://discourse.linuxserver.io/t/setup-a-run-aafter-script-in-duplicati/1303
