### ISSUE TITLE
Missing mysqldump

### ISSUE THREAD

**Issue by bd8392** [linuxserver/docker-duplicati#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

I want to execute a mysqldump on run script before...but mysqldump is missing
------------------------------

## Expected Behavior

Mysqldump-Script should execute

## Current Behavior

Backup failure, as there is no mysqldump in the container

## Steps to Reproduce

1. Get container
2. Configure mysqldump script and backup
3. Place script in duplicati and configure run script before
4. See log exits with 255 because of missing mysqldump

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

Preinstalled (rancheros)
## Command used to create docker container (run/create/compose/screenshot)

Like in docks
## Docker logs

See above

**Comment by CHBMB** [comment]
`mysqldump` can be installed with  `mariadb-client` from the ubuntu repository.  

[Best achieved using this method.](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/)

```
#!/bin/bash

echo "**** installing mariadb-clent ****"
apt update
apt install mariadb-client
```
