### ISSUE TITLE
Being asked for password when accessing webgui, fresh install

### ISSUE THREAD

**Issue by moorsey** [linuxserver/docker-duplicati#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Should be no password on first access

## Current Behavior
Am asked for a password, feel like I'm missing something here, lots of Googling, can't see any similar issues to what I am seeing

## Steps to Reproduce
Create docker from CLI using:

`docker run -d \
--name=duplicati \
-e PUID=1000 \
-e PGID=100 \
-e TZ=Europe/London \
--net=proxy \
-v /sharedfolders/dockerdata2/duplicati/config:/config \
-v /sharedfolders/backups/duplicati:/backups \
-v /sharedfolders:/source \
--restart unless-stopped \
linuxserver/duplicati`

Have also tried adding:
`-e FILE__PASSWORD=/sharedfolders/dockerdata2/duplicati/password/secret \`

and....

`-e CLI_ARGS=webservice-password \`

First option does not set the password as per my "secret" file contents
Second option does not force the password to blank

## Environment
**OS:**      OpenMediaVault
**CPU architecture:** x86_64   
**How docker service was installed:**      
OpenMediaVault plugin installed

## Command used to create docker container (run/create/compose/screenshot)
As above

## Docker logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    100
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-scripts: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-scripts: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.

**Comment by CHBMB** [comment]
I can't reproduce this, only way I can see this happening is if you've previously installed and set a password and are reusing the config.  

Here's my fresh install:

https://i.imgur.com/Jz9Jcg9.png

Try `rm -rf /sharedfolders/dockerdata2/duplicati/config` and reinstall.

**Comment by IronicBadger** [comment]
I can't replicate either. I see the same behavior as @CHBMB.

`docker run --rm --name=duplicati -p 8200:8200 -e PUID=1000 -e PGID=1000 -e TZ=Europe/London   linuxserver/duplicati`.

![image](https://user-images.githubusercontent.com/2773080/93688939-dcd25900-fa97-11ea-8698-dc8e7adf7d2b.png)


I did note that you have set the GID to 100 not 1000, was that a typo? Like CHBMB said, you are probably accidentally reusing a config without meaning to.

Also, if you were not aware you might get more immediate support via the LSIO [discord](https://discord.gg/YWrKVTn) channels.

**Comment by moorsey** [comment]
Hi both, thanks for checking this.

I did think it was some old config from somewhere, ran a "rm -rf" inside my config folder, but apparently this does not remove hidden dirs and there was a ".config" inside here.  So cleared all that, ran spun the docker and all good.  @CHBMB suggestion pushed me to double check here, so thanks!

Yeah, the 100/1000 thing has always seemed odd, but that's how it is in OpenMediaVault, on my install anyway.  Seems to be working fine.

Sorry for the noise on here!
