### ISSUE TITLE
Capabilities not working for Docker Image

### ISSUE THREAD

**Issue by CuriousEl3phant502** [linuxserver/docker-duplicati#41]
I'm trying to assign capabilities in order to backup files with a service account (non-root) for security reasons. However, the regular user is never able to backup the files it does not own without errors (and missing files in the backup- I checked this). On the other hand, when I switch the user in the env vars to root it backs up with no warnings and all files are indeed backed up.

Here is the docker compose:

version: "3.9"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    cap_add:
      - DAC_READ_SEARCH
    environment:
      - PUID=1000 #service account ID
      - PGID=1000 # service account group id
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - </path/to/appdata/config>:/config
      - </path/to/backups>:/backups
      - </path/to/source>:/source
    ports:
      - 8200:8200
    restart: unless-stopped

Even when assigning capabilities of read all access (DAC_READ_SEARCH) or "privledged: true" or cap_add: all i still get this error and the files are not backup:

> Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: /path/to/some/file/not/owned/by/user/1000

I'm expecting to get a complete backup with no errors (as happens if i try to run it as user 0 and group 0 or root.)

------------------------------

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64 Intel
**Docker Installation: Official Repo

Command Used to create docker container:
_docker-compose up -d_

I used the Duplicati UI to create and run the backups. 

--------------------------------------------------------

I did attach to my container, installed setcap, and was able to run the following:

_apt-get update
apt-get install -y libcap2-bin
setcap cap_dac_read_search=+ep /usr/bin/mono-sgen
s6-setuidgid abc mono /app/duplicati/Duplicati.CommandLine.exe backup .... (backup command exported from the UI)_

After running this I checked the logs in the UI. It completed without warnings. Maybe setcap cap_dac_read_search=+ep /usr/bin/mono-sgen could be run somewhere services.d/duplicati/run file?

As a matter of control if i run the following
s6-setuidgid abc mono /app/duplicati/Duplicati.CommandLine.exe backup .... (backup command exported from the UI) right After restarting a new container, but **without running set cap commnand**, it gives me the same errors i see in the log files in the UI.

> Error in the cmd line w/o running setcap "Error reported while accessing file: /source/my/source/path/ => Access to the path... '

I can't think of any downsides to something along these lines (but maybe someone has a better idea). I can't think why someone would not want their own user to be able to read all the files they're trying to backup that they purposely added as a volume. I see a lot people running as user/group root for this problem in guides.

**Comment by webash** [comment]
@CuriousEl3phant502 did you find a resolution to this using Docker capabilities flags? I'm experiencing the same issue in trying to pass the `CAP_DAC_READ_SEARCH` or `CAP_DAC_OVERRIDE` through to the duplicati backup process; I can see that the `root` processes in the container have the privilege, but not the `abc` user/`abc` user's processses:

```
root@80c5625f013a:/# ps aux
    USER     PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
       0       1  0.0  0.0    200    20 ?        Ss   16:40   0:00 /package/admin/s6/command/s6-svscan -d4 --
       0      16  0.0  0.0    204    20 ?        S    16:40   0:00 s6-supervise s6-linux-init-shutdownd
       0      19  0.0  0.0    196     4 ?        Ss   16:40   0:00 /package/admin/s6-linux-init/command/s6-lin
       0      27  0.0  0.0    204    16 ?        S    16:40   0:00 s6-supervise s6rc-oneshot-runner
       0      28  0.0  0.0    204    16 ?        S    16:40   0:00 s6-supervise s6rc-fdholder
       0      35  0.0  0.0    180     4 ?        Ss   16:40   0:00 /package/admin/s6/command/s6-ipcserverd -1
       0     156  0.0  0.0    204    16 ?        S    16:40   0:00 s6-supervise duplicati
   abc     158  0.0  0.4 146116 35276 ?        Ssl  16:40   0:00 mono Duplicati.Server.exe --webservice-inte
   abc     166 49.2  1.8 2111480 148860 ?      Sl   16:40  13:12 /usr/bin/mono-sgen /app/duplicati/Duplicati
       0     214  0.0  0.0   6872  3400 pts/0    Ss   17:03   0:00 /bin/bash
       0     554  0.0  0.0   8468  2752 pts/0    R+   17:07   0:00 ps auxn
root@80c5625f013a:/# getpcaps 166
166: =
root@80c5625f013a:/# getpcaps 158
158: =
root@80c5625f013a:/# getpcaps 156
156: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+ep
```

**Comment by maxime1992** [comment]
Hey guys, has anyone found an answer to this please?

**Comment by webash** [comment]
Nope. I figure I probably need to use another image, as this one is a bit too complex to wrap my head around trying to pass the right capabilities through so that Duplicati has the appropriate rights to backup all files

**Comment by maxime1992** [comment]
FYI @webash you can follow [here](https://github.com/linuxserver/docker-duplicati/issues/59) as well in case I get an answer there

**Comment by webash** [comment]
@maxime1992 subscribed, thanks

**Comment by CuriousEl3phant502** [comment]
@webash Nope. I just figured linuxserver has some automated stuff to keep images up to date, but other than that assumed it's abandonware since I never got a response (now it's almost been 2 years w/o a response). I just gave up and ran as root.  I just leave the container down and run on demand only.

**Comment by aptalca** [comment]
If the files you're trying to back up are owned by root, then you can run this container with PUID/PGID set to 0. It's one of very few scenarios we recommend running as root for.

Why would you assume abandonware because we never answered you about capabilities? We never brought up capabilities anywhere. It's not something we support.
