### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by Goro2030** [linuxserver/docker-duplicati#43]
------------------------------

## Expected Behavior

When using this in the ENVIRONMENT section, it is expected that the password be set to that specific one, with the intent to reset it in the database ( due to a forgotten password):

## Current Behavior

The parameter is ignored, and the password does not change.

## Steps to Reproduce
1. Modify docker-compose.yml
2. Try to login using the new password set in the environment variable
3. Get error: "Login failed: Unauthorized"

## Environment
**OS:** Ubuntu
**CPU architecture:** Arm64
**How docker service was installed:** Official repo

## Command used to create docker container (run/create/compose/screenshot)

Used docker-compose as per your recommended standard.

  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - CLI_ARGS=webservice-password=supersecretpassword
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
      - CLI_ARGS= #optional
    volumes:
      - ~/configs/duplicati/config:/config
      - ~/backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by homerr** [comment]
Have you declared the same directive twice - highlighted bold below...

```
duplicati:
image: ghcr.io/linuxserver/duplicati:latest
container_name: duplicati
environment:
**- CLI_ARGS=webservice-password=supersecretpassword**
- PUID=0
- PGID=0
- TZ=America/Santiago
**- CLI_ARGS= #optional**
volumes:
- ~/configs/duplicati/config:/config
- ~/backups:/backups
- /:/source
ports:
- 8200:8200
restart: unless-stopped
```

**Comment by Goro2030** [comment]
Thanks! That solved it :)

Saludos,
Mariano
[image: cloudHQ] <https://www.free-email-tracker.com> Powered by
cloudHQ <https://www.free-email-tracker.com>
