### ISSUE TITLE
Add socker binary so that you can run exec on running containers

### ISSUE THREAD

**Issue by BaseCrusher** [linuxserver/docker-duplicati#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Adding the docker binary to this image would make it possible to bind `/var/run/docker.sock` to the container and then run docker exec on containers running on the host. You could for example run postgres dump on a postgres container before executing a backup.

------------------------------

## Desired Behavior

In the summery

## Alternatives Considered

Run another scheduler parallel to duplicati that can execute commands on other containers.

**Comment by aptalca** [comment]
We have a universal docker mod

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-docker
