### ISSUE TITLE
Duplicati ignores puid:pgid and create folders/files with root

### ISSUE THREAD

**Issue by marouamghar** [linuxserver/docker-duplicati#50]
The puid/pgid are read by the container, as shown by the logs.

## Expected Behavior
upon first run, it should create the backups folder using abc mapped to 1000, similarly to other containers using 1000:1000

## Current Behavior
$ ls -l
drwxr-xr-x 2 root root 4.0K May 10 18:27 backups

## Steps to Reproduce
1.Pass PUID=1000, PGID=1000
2.Delete the backups folder that was created before
3.Recreate the image
4.The folder backups will be created again, with the wrong users

## Environment
**OS:**
**CPU architecture:** arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
same as in github

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by aptalca** [comment]
That folder is not created by the container. It is created by docker when you map it. And docker creates it as root.

We only fix the permissions of the config folder. Other media or data folder permissions are the user's responsibility. It's best if you create the folders on your host before creating the container so they are owned by your user.

**Comment by marouamghar** [comment]
My bad, thanks !
