### ISSUE TITLE
duplicati-cli is missing

### ISSUE THREAD

**Issue by eprouty** [linuxserver/docker-duplicati#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Duplicati normally ships with a command line tool as outline here: https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/

The docker image provided by duplicati makes reference to this as well, https://hub.docker.com/r/duplicati/duplicati/

We should be able to run `duplicati-cli` from within this container or using commands such as `docker run --rm linuxserver/duplicati duplicati-cli help`

## Current Behavior
`bash: duplicati-cli: command not found`

## Steps to Reproduce

1. Start duplicati container
2. Attempt to use `duplicati-cli`

**Comment by aptalca** [comment]
The tool should be there, but we don't support running manual commands inside the container unless we ask you to. If you really need to do that for a justified reason, you may seek help in [our discord server](https://discord.gg/YWrKVTn?target=_blank)

**Comment by macross5** [comment]
Could someone run the cli? I get...

`/app/duplicati/Duplicati.CommandLine.exe help
bash: /app/duplicati/Duplicati.CommandLine.exe: Permission denied`

**Comment by thehale** [comment]
The following command works for accessing the CLI:
```
docker exec -it duplicati bash
mono app/duplicati/Duplicati.CommandLine.exe help
```

Per the [Duplicati docs](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#how-to-use-the-duplicati-command-line-tool), `duplicati-cli` is just an alias for `mono Duplicati.CommandLine.exe`.
