### ISSUE TITLE
Image won't start after update

### ISSUE THREAD

**Issue by Inrego** [linuxserver/docker-duplicati#56]
I set up my Duplicati a little while ago, and then kinda just left it to do its thing.
Now I'm in need to check a backup, and I figure that it hasn't been working since early last month.
In fact, I can't even access the web interface. To make sure it wasn't some corrupted config, I booted up a new image without any volume mappings, and it's still not loading.

EDIT: btw I'm running watchtower, so the image was automatically updated

**Comment by j0nnymoe** [comment]
Would be helpful if you'd provided information for the issue template.

**Comment by Inrego** [comment]
---
name: Bug report
about: Create a report to help us improve

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]





------------------------------

## Expected Behavior

Web interface should load when visiting the url on the mapped port.
## Current Behavior

Infinite loading
## Steps to Reproduce


1. Start docker container
2. Open url for the port in browser

## Environment
**OS:** Ubuntu
**CPU architecture:** x64
**How docker service was installed:**
I don't remember. Official installation method



## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/2242329/188111247-204ef5bd-001b-4c1b-b5bf-c95d44e840b4.png)

![image](https://user-images.githubusercontent.com/2242329/188111301-07f2d8bb-e9b1-4937-8fb5-bf332cc863aa.png)


## Docker logs


> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service 00-legacy: starting
> s6-rc: info: service 00-legacy successfully started
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/01-envfile
> cont-init: info: /etc/cont-init.d/01-envfile exited 0
> cont-init: info: running /etc/cont-init.d/01-migrations
> [migrations] started
> [migrations] no migrations found
> cont-init: info: /etc/cont-init.d/01-migrations exited 0
> cont-init: info: running /etc/cont-init.d/02-tamper-check
> cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
> cont-init: info: running /etc/cont-init.d/10-adduser
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> cont-init: info: /etc/cont-init.d/10-adduser exited 0
> cont-init: info: running /etc/cont-init.d/30-config
> cont-init: info: /etc/cont-init.d/30-config exited 0
> cont-init: info: running /etc/cont-init.d/90-custom-folders
> cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
> cont-init: info: running /etc/cont-init.d/99-custom-scripts
> [custom-init] no custom files found exiting...
> cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service init-mods: starting
> s6-rc: info: service init-mods successfully started
> s6-rc: info: service init-mods-package-install: starting
> s6-rc: info: service init-mods-package-install successfully started
> s6-rc: info: service init-mods-end: starting
> s6-rc: info: service init-mods-end successfully started
> s6-rc: info: service init-services: starting
> s6-rc: info: service init-services successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun duplicati (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> s6-rc: info: service 99-ci-service-check: starting
> [ls.io-init] done.
> s6-rc: info: service 99-ci-service-check successfully started

**Comment by Inrego** [comment]
Sorry, hadn't seen the template beforehand. Here you go

**Comment by Inrego** [comment]
I tried rolling back to an older version and issue persists. I'm gonna have to dig deeper and assume it's an issue on my end.
