### ISSUE TITLE
Unable to process paths containing Unicode characters

### ISSUE THREAD

**Issue by Sitwon** [linuxserver/docker-duplicati#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I am running this container on a NAS. Every time a backup job runs, I get the following warnings on the same file paths. The thing all of the flagged paths have in common is that there is at least one non-ASCII character in the path.

```... [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-PathProcessingError]: Failed to process path: ...```
------------------------------

## Expected Behavior

Paths containing Unicode characters should be processed the same as paths containing all ASCII characters.

## Current Behavior

Paths containing Unicode characters are being excluded from the backup due to the above PathProcessingError.

## Steps to Reproduce

1. Create a backup job.
2. Add a file in the source directory for the backup job that contains a Unicode character in the filename.
3. Run the backup job.
4. Check the logs after the backup job has finished running.

## Environment
**OS:** QNAP Firmware version	QTS 5.0.1.2173 Build 20221001
**CPU architecture:** x86_64
**How docker service was installed:**

Installed from the official docker repo, via the Container Station app.

## Docker logs

```-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun duplicati (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started```

**Comment by drizuid** [comment]
We need your docker and/or docker compose version and your docker run or docker compose yaml file. Currently, this seems like an application issue rather than a container issue which would need to be reported to the upstream devs.
