### ISSUE TITLE
A timeout event with bad impact on all tasks in duplicati

### ISSUE THREAD

**Issue by huangwb8** [linuxserver/docker-duplicati#58]
Recently I found a "bug" of duplicati.

Supposed I backup files from A to B.  Sometimes, the connection between A and B might be instable and interrupted. 

A right way to deal with this situation is to stop the task, send a warning email, and begin the next task. However, duplicati just stucks for a long time (days or months) without any warnings and errors.

This feature seriously impairs the stableness of duplicati. Any suggestions?

**Comment by Roxedus** [comment]
My suggestion is to report this to the correct upstream project.

**Comment by huangwb8** [comment]
@Roxedus Thank you very much!
