### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by flecmart** [linuxserver/docker-duplicati#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Timezone is not set correctly:

![image](https://user-images.githubusercontent.com/10167243/228204055-ac31a9ae-5085-4505-9328-a00ffc3f09cd.png)

### Expected Behavior

Timezone should be reflected in container when TZ environment variable is set.

### Steps To Reproduce

1. Use the default docker-compose example from https://docs.linuxserver.io/images/docker-duplicati#docker-compose-recommended-click-here-for-more-info
2. Change TZ to `TZ=Europe/Berlin`
3. `docker-compose up -d`
4. `docker exec -it duplicati bash`
5. Inside the container: `cat /etc/timezone`

### Environment

```markdown
- OS: debian bullseye 64bit
- How docker service was installed:
https://docs.docker.com/engine/install/debian/
```

### CPU architecture

arm64

### Docker creation

```bash
version: '2.1'

services:
    duplicati:
        image: lscr.io/linuxserver/duplicati:latest
        container_name: duplicati
        environment:
            - PUID=0
            - PGID=0
            - TZ=Europe/Berlin
          # - CLI_ARGS= #optional
        volumes:
            - ~/duplicati/config:/config
            - ~/duplicati/local_backups:/backups
            - /home/pi:/source
        ports:
            - 8200:8200
        restart: unless-stopped
```

### Container logs

```bash
$ docker logs duplicati
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
What does `date` return inside the container?

**Comment by flecmart** [comment]
```
root@3d016c1739c1:/# date
Tue Mar 28 03:03:54 PM CEST 2023
```

It aligns with my local time right now, but it is still the wrong timezone, because in Europe/Berlin we have 1h difference in summer vs. winter. I noticed by chance because some days ago it switched to summer time here, and my backup jobs ran an hour late.

**Comment by flecmart** [comment]
This is still an issue for me.

**Comment by aptalca** [comment]
It looks like `date` is returning the correct time zone so setting the TZ is working as expected. If it's not abiding by the daylight saving time in your timezone, either you're on an old image, or there is an issue way upstream of us. We don't control the daylight savings times. We only set the timezone.

**Comment by flecmart** [comment]
Okay, I migrated to another hardware and double checked the date output. It seems to be correct now - thanks for your respone. I am closing the issue.
