### ISSUE TITLE
[BUG] GUI not working in latest / 2.0.7

### ISSUE THREAD

**Issue by naelfe** [linuxserver/docker-duplicati#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The gui does not work after updating to latest (2.0.7). I don't get prompted for a password and can't login. I only get the message "Unable to connect".
When going back to 2.0.6 the gui works and I can log in, but the tasks don't run because of an update to the underlying DB which seems to be too new for 2.0.7. I suppose it was updated in 2.0.7.

Already stated here https://forums.unraid.net/topic/56610-support-linuxserverio-duplicati/?do=findComment&comment=1292317
Another user seemed to have a similar issue which might have been resolved using another browser. But for me the behavior is consistent through firefox, chrome and edge.

### Expected Behavior

gui should work and prompt me for my login PW.

### Steps To Reproduce

With **unraid 6.12.3** and the docker app https://forums.unraid.net/topic/56610-support-linuxserverio-duplicati/ updated to latest release I open the web-UI with "IP:8200" (no reverse proxy, hostname, anything) and I get "unable to connect" with firefox, chrome and edge. (also tried private mode as soggested in another issue that was resolved, but did not work)

When re-creating the docker with 2.0.6 I can log in again, but the tasks don't work a anymore because of a DB version conflict.

### Environment

```markdown
- OS: unraid 6.12.3
- from community applications plugin in unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='duplicati'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="nv"
  -e HOST_CONTAINERNAME="duplicati"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8200]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/duplicati-icon.png'
  -p '8200:8200/tcp'
  -v '/mnt/user/tmp/':'/tmp':'rw'
  -v '/mnt/user/data_backup/':'/backups':'rw'
  -v '/mnt/user/':'/source':'rw'
  -v '/mnt/user/appdata/duplicati':'/config':'rw' 'linuxserver/duplicati'

6b237d3504ae84a6a7b26ecacad5b16e03af7cdcb7ce98a0b35284d5e5f21e5c

The command finished successfully!
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by thespad** [comment]
I've just done a clean install, and it seems to be working correctly:

![image](https://github.com/linuxserver/docker-duplicati/assets/8425502/1f8d79a7-ae23-4161-9ee7-6589967f9068)

It's possible there's an upstream issue with migration to the new version, especially if there are DB changes. Unfortunately I don't think Duplicati logs to file anywhere meaningful, you'd have to dig into the sqlite database to find anything.

**Comment by naelfe** [comment]
Hm... thanks for the tip. I tried a clean one as well:

docker run
  -d
  --name='duplicati_test'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="nv"
  -e HOST_CONTAINERNAME="duplicati_test"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8200]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/duplicati-icon.png'
  -p '8200:8200/tcp'
  -v '/mnt/user/tmp/':'/tmp':'rw'
  -v '/mnt/user/data_backup/':'/backups':'rw'
  -v '/mnt/user/':'/source':'rw'
  -v '/mnt/user/appdata/duplicati_test':'/config':'rw' 'linuxserver/duplicati'

b99306a5d45100c66214493e84af7a062085461f05554aa62d3566c21d60e19d

The command finished successfully!

Simply changed the name of the docker and the appdata folder to something else (duplicati_test) **but** it does not work:
![image](https://github.com/linuxserver/docker-duplicati/assets/108142825/99ebbf2a-7726-47d9-a7c7-4da70ee8f3bd)

I suppose that one should work, if it would have been an upgrad issue, right?

**Comment by thespad** [comment]
It should indeed. Can you remove the test container and try
```
docker run -d --rm --name=duplicati --tmpfs /config -p 8200:8200 linuxserver/duplicati
```
And see if that one works.

**Comment by naelfe** [comment]
Hm... I'm not sure :/
I stopped the original container and removed the second one (test).

Then I run docker run -d --rm --name=duplicati_test --tmpfs /config -p 8200:8200 linuxserver/duplicati
but I think it was not created correctly in unraid
![image](https://github.com/linuxserver/docker-duplicati/assets/108142825/76a06e5c-be28-4950-8993-018f1d1d7bac)
It seems to be missing the port mapping

**Comment by thespad** [comment]
Unraid's docker UI is very basic, if you run `docker ps | grep duplicati` you'll see the container and the port mapping/bindings.

**Comment by naelfe** [comment]
I will check that after lunch. currently I have the old container running (without gui) and will check if the daily schedule at 13:00 will copy anything to its destination. That way I'll know if its the whole container, or only the gui.

**Comment by naelfe** [comment]
Another update:
I just noticed that the container I had running was created using the left unraid-app.
![image](https://github.com/linuxserver/docker-duplicati/assets/108142825/a83c3c5b-a4c8-4fc0-808e-221193bff84c)
Also created a 2nd one with the "new" app, but it behaves the same. Even though it uses the emask parameter which the old one does not :/

**Comment by naelfe** [comment]
And another update:
lscr.io/linuxserver/duplicati:development seems to work.
I will try to start the old one in 2.0.6 to potentially export the backup configs and import them in the new development container.
Will post an update later this evening

**Comment by naelfe** [comment]
I think it is/was some issue with the update from 2.0.6 to 2.0.7.
When playing around with another container and trying to the carnary channel I wanted to start tho old container with 2.0.6 and export my backup configuration from there (which worked).
Then I figured: why export and import everything to a new container, when I can override my appdata conent with my latest backup. I then could logged in with 2.0.6 and was informed (in duplicati) about the update, which I downloaded from the container gui itself.
After that, I changed to tag to :latest and now it seem to be working- but I have to re-create the backup databases in duplicati, because the target file are a few days newer then my latest appdata backup.

So far: seems to work again- even though I don't know how it happend

**Comment by EVOTk** [comment]
Hello,
I'm have same issue. GUI not working :(

Same as you, nothing special in the logs

**Comment by josephpons** [comment]
I have the same issue, it's to do with Cookies, I haven't had time to dig any deeper but this is the error:
![image](https://github.com/linuxserver/docker-duplicati/assets/20292875/9b598010-1f53-4e48-8c65-d982d0aa4e9d)

It seems to be a large session cookie. When I delete it, I get the login screen, then receive 400's once I log in.

**Comment by Potajito** [comment]
Weird, but I'm getting the same behaviour than previous user. GUI works on chrome but not on firefox 120.

**Comment by j0nnymoe** [comment]
We just package what's provided by duplicati, best to check their forums for support.

**Comment by EVOTk** [comment]
> Same here. Works on Safari, not on Firefox

For me, clearing the cookies on Firefox solved my problem.
