### ISSUE TITLE
Not honoring PGID/PUID environment variables

### ISSUE THREAD

**Issue by edgard** [linuxserver/docker-duplicati#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by homerr** [comment]
Stale issue and closed, does not appear to be an issue anywhere else (even for myself) so could have been an issue in a build earlier this year.
