### ISSUE TITLE
[FEAT] Backup from Remote host

### ISSUE THREAD

**Issue by NazgulCoder** [linuxserver/docker-duplicati#73]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello, I've seen duplicati allows you to backup folders from your host to cloud services such as FTP, SFTP, WebDav, DropBox, Gdrive etc.

Is it possible to implement a feature that backups data from a remote FTP/SFTP server and saves it locally?

### Reason for change

see above

**Comment by j0nnymoe** [comment]
You need to ask them, not us.
