### ISSUE TITLE
connection time out to remote SFTP

### ISSUE THREAD

**Issue by HornetNL** [linuxserver/docker-duplicati#9]
Synology DSM - DSM 6.2-23739 Update 2
Docker 17.05.0-0379
linuxserver- duplicati build 94

Hi,

When using the Duplicati docker container I get a connection time out trying to connect to an external SFTP server.

I am seeing this in the log:

`17:38:05 Renci.SshNet.Common.SshOperationTimeoutException: Session operation has timed out stdout
17:38:05  at Renci.SshNet.Session.WaitOnHandle (System.Threading.WaitHandle waitHandle, System.TimeSpan timeout) [0x00065] in <502177f7126d48e4be01a83c8cdb4c79>:0 stdout
17:38:05  at Renci.SshNet.Session.WaitOnHandle (System.Threading.WaitHandle waitHandle) [0x0000d] in <502177f7126d48e4be01a83c8cdb4c79>:0 stdout
17:38:05  at Renci.SshNet.Session.Connect () [0x00258] in <502177f7126d48e4be01a83c8cdb4c79>:0 stdout
17:38:05  at Renci.SshNet.BaseClient.Connect () [0x00077] in <502177f7126d48e4be01a83c8cdb4c79>:0 stdout
17:38:05  at Duplicati.Library.Backend.SSHv2.CreateConnection () [0x00107] in <29d74a8631ec474595c3d5eee75c41bf>:0 stdout
17:38:05  at Duplicati.Library.Backend.SSHv2+<List>d__39.MoveNext () [0x0002c] in <29d74a8631ec474595c3d5eee75c41bf>:0 stdout
17:38:05  at Duplicati.Library.Interface.BackendExtensions.TestList (Duplicati.Library.Interface.IBackend backend) [0x00017] in <b7a5128865b14f37a66544de6a7ae6fb>:0 stdout
17:38:05  at Duplicati.Library.Backend.SSHv2.Test () [0x00000] in <29d74a8631ec474595c3d5eee75c41bf>:0 stdout
17:38:05  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000b7] in <670b0e4a9ae144208688fcb192d20146>:0 stdout
17:38:05  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00091] in <670b0e4a9ae144208688fcb192d20146>:0 stdout
17:38:05  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x0026e] in <670b0e4a9ae144208688fcb192d20146>:0 stdout
`

Connecting to a local SFTP server works, so I tried opening a bash shell, apt-get install ssh and do sftp remote_username@remote_host to the same external SFTP server as previously in the GUI and that works also. Also tried installing duplicati on my Windows machine (sorry, am a M$ triple MCITP as it is my job (gotta whore some money to keep the family alive)), and that worked straight out of the box. Could setup an Linux box with Duplicati as well but given the other troubleshooting steps I think that would work as well....

 Is this something you've seen before regarding your container or should I ask this question over at Duplicati themselves?

Thanks a lot in advance for reviewing my question!

**Comment by gertaylor** [comment]
hey,

Did you find a resolution to this issue?

Cheers

**Comment by HornetNL** [comment]
Unfortunatly not… :(

**Comment by j0nnymoe** [comment]
I've had no issues using SFTP as a backup location on duplicati since we released the container. The host is just Debian 9 with OpenSSH. I would suggest reporting the issue directly to duplicati so they can confirm it's an issue you are having with your container or duplicati itself.

**Comment by the-dag** [comment]
I am using Renci SFTP (the SSH.NET nuget package, version 2016.1.0) in a different context, and the code is running in Docker on a Debian 10-based image (mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim). I don't know exactly what the server side is, other than its some Linux box with OpenSSH. 

I am getting the exact same symptom. We have determined that connections are not closed by the client. Over time this builds up a lot of idle sessions on the server and it eventually runs out of resources, leading to new connection attempts timing out.

I suspect the SSH.NET package is buggy (at least on netcore), but I can't rule out that disconnecting is prevented due to a firewall issue or something like that.

**Comment by the-dag** [comment]
Related: https://github.com/sshnet/SSH.NET/issues/133
