### ISSUE TITLE
[BUG] incorrect environment variable key with two underscores renders duplicati useless and causes login issues

### ISSUE THREAD

**Issue by marcxm** [linuxserver/docker-duplicati#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mydudes, you've made mistake and you are using environment variable with TWO underscores! this renders duplicati useless, as users cannot log in anymore ... double underscore is right after "DUPLICATI".

"- DUPLICATI__WEBSERVICE_PASSWORD= #optional"

### Expected Behavior

Well, ability to log into the instance.

### Steps To Reproduce

User provided docker-compose.yml and set password.

### Environment

```markdown
- OS: doesn't matter
- How docker service was installed: doesn't matter
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
no meaningful output, because this is configuration key typo.
```

**Comment by Roxedus** [comment]
How does the double underscores break Duplicati? It is a very common scheme, and follows the variable the official image is using.

**Comment by marcxm** [comment]
hm, then it's something else I guess. Anyhow, no option to log in with correct password.

**Comment by Roxedus** [comment]
To help with that, fill the issue template fully, as it is now incomplete.

**Comment by aptalca** [comment]
My dude, it works just fine here. I use it myself.
